/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.switcher.views.natives.views.mediators.GridsViewMediatorTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var flexUnitTests_switcher_views_natives_views_mediators_GridsViewMediatorTest_obj:flexUnitTests.switcher.views.natives.views.mediators.GridsViewMediatorTest;
	}
}